const data = [{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_A', 'x': 0, 'y': 0, 'path': '..|src|index.js', 'id': 'A' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_A', 'x': 0, 'y': 0, 'path': '..|src|App.test.js', 'id': 'B' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_A', 'x': 0, 'y': 0, 'path': '..|src|routes.js', 'id': 'C' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_A', 'x': 0, 'y': 0, 'path': '..|src|setupTests.js', 'id': 'D' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_A', 'x': 0, 'y': 0, 'path': '..|src|App.js', 'id': 'E' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_D', 'x': 0, 'y': 0, 'path': '..|src|pages|Home|layout.js', 'id': 'F' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_D', 'x': 0, 'y': 0, 'path': '..|src|pages|Home|index.js', 'id': 'G' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_E', 'x': 0, 'y': 0, 'path': '..|src|pages|Diagram|memory.js', 'id': 'H' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_E', 'x': 0, 'y': 0, 'path': '..|src|pages|Diagram|Diagram.js', 'id': 'I' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_F', 'x': 0, 'y': 0, 'path': '..|src|pages|FauxForce|layout.js', 'id': 'G' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_F', 'x': 0, 'y': 0, 'path': '..|src|pages|FauxForce|Controls.js', 'id': 'K' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_F', 'x': 0, 'y': 0, 'path': '..|src|pages|FauxForce|index.js', 'id': 'L' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_F', 'x': 0, 'y': 0, 'path': '..|src|pages|FauxForce|guilogic.js', 'id': 'M' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_F', 'x': 0, 'y': 0, 'path': '..|src|pages|FauxForce|ReadJson.js', 'id': 'N' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_H', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|layout.js', 'id': 'O' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_H', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|index.js', 'id': 'P' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_I', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|redux|types.js', 'id': 'Q' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_I', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|redux|actions.js', 'id': 'R' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_I', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|redux|index.js', 'id': 'S' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_I', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|redux|reducers.js', 'id': 'T' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_I', 'x': 0, 'y': 0, 'path': '..|src|pages|ABCDocuments|redux|thunks.js', 'id': 'U' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_G', 'x': 0, 'y': 0, 'path': '..|src|pages|SecondPass|layout.js', 'id': 'V' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_G', 'x': 0, 'y': 0, 'path': '..|src|pages|SecondPass|logic.js', 'id': 'W' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_G', 'x': 0, 'y': 0, 'path': '..|src|pages|SecondPass|Controls.js', 'id': 'X' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_G', 'x': 0, 'y': 0, 'path': '..|src|pages|SecondPass|memory.js', 'id': 'Y' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_G', 'x': 0, 'y': 0, 'path': '..|src|pages|SecondPass|index.js', 'id': 'Z' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_L', 'x': 0, 'y': 0, 'path': '..|src|pages|ForceDirectedGraph|layout.js', 'id': 'AA' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_L', 'x': 0, 'y': 0, 'path': '..|src|pages|ForceDirectedGraph|logic.js', 'id': 'AB' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_L', 'x': 0, 'y': 0, 'path': '..|src|pages|ForceDirectedGraph|Controls.js', 'id': 'AC' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_L', 'x': 0, 'y': 0, 'path': '..|src|pages|ForceDirectedGraph|index.js', 'id': 'AD' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_N', 'x': 0, 'y': 0, 'path': '..|src|redux|index.js', 'id': 'AE' },
{ 'sy': 0, 'sx': 0, 'angle': 0, 'parent': '_N', 'x': 0, 'y': 0, 'path': '..|src|redux|reducers.js', 'id': 'AF' },
]

export {
    data
}